### ISSUE TITLE
Desktop integration

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#31]
Could be nice if we managed to get file managers to detect .osu files and spawn oshu automatically when double-clicking on them.

This issue is specifically targeted at Gnome and KDE users, so we had better test on these two environments. However, it's common XDG stuff.

0. Make a logo.
1. Make a oshu.desktop file for share/applications/
2. Make an x-osu.xml file for share/mime/packages/
3. Install them with automake.
4. Make a packaging guideline explaining how to use xdg-mime to make oshu the default application.

Once this is ready, the next step is #35.

**Comment by lanodan** [comment]
I’ve ~done
1. https://github.com/lanodan/oshu/commit/41a99fa4be523e2a4338c960852720f4f83d83df
2. https://github.com/lanodan/oshu/commit/c0f7d9c67f3e5cdf1dba501f526dc44784cc49ab
4. https://github.com/lanodan/oshu/commit/af7e8c8e3f56753e5e34e8f37ef38fc7afa47d7e

Feel free to adapt theses to your liking/needs.
I’ll maybe do 0. And I tend to break automake stuff… so I’ll probably not do 3.

**Comment by fmang** [comment]
@lanodan That's a very good start.

I've told about the project to a super good graphist friend of mine. Don't spend too much time on the logo now.

We can't expect the user to install the desktop integrations. Most files should be installed with autoconf, and the final step with xdg-mime should be handled by post-installation procedures for distribution packagers, or manually.

**Comment by fmang** [comment]
I've moving this to milestone 1.7, because the new UI features in 1.6 are already quite a move, especially in the code.

1.7 will focus on desktop integration, and nothing but that I think.

**Comment by fmang** [comment]
Done and packaged. Thank you lanodan for contributing the desktop files.

The files are deployed with `make install` in the standard directories, so the regular regular should not need bother with the install commands.

The logo should come soon enough, I'll add it when it's ready. Issue #62.
