### ISSUE TITLE
Beatmap indexer

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#35]
We could use the web browser to display a fancy beatmap index, and when the user opens a .osu file, the browser would start oshu.

This could be even generated using a bash script, but for cross-platform support, C remains a better option.

The tool could look like this:

- `oshu-lib browse`: spawn the web browser at $LIBRARY/browser/index.html. This is how oshu should appear in an application menu.
- `oshu-lib add beatmap.osz`: unpack the beatmap in $LIBRARY/beatmaps/. This should be the default action for .osz files.
- `oshu-lib update`: rebuild the HTML documents, in case the library was externally changed.

After #31, oshu should be the default choice for .osu files, and links can be more explicit with:

```
<a href="beatmap.osu" type="application/x-osu">Beatmap</a>
```

**Comment by lanodan** [comment]
I think instead of bash (non-standard) it could be POSIX Shell if C isn’t used.

**Comment by fmang** [comment]
The indexer is ready, even though it's a bit rought around the edges. I mean, it's a total prototype.

It will be shipped with oshu 2.0, and the more advanced features will appear progressively.
