### ISSUE TITLE
Support lower hardware specs

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#43]
Today, I've tried to play oshu! on my Raspberry Pi 2. The first try was a disaster, but tweaking the right settings made the game playable.

1. Accelerated graphics are a lie. By forcing the software renderer in the SDL_Renderer, the performance got *much* better. Maybe it has to do with my X configuration, or maybe fbturbo isn't meant for that.
2. The default window size is also a significant factor. The common textures are generated when the game start, taking into account the window size at that time. Starting with a smaller screen will generate smaller textures. Alternatively, an environment variable could control the texture quality disregarding the window size. At 640×480 the game got playable, even though it skipped frames.
3. The background is currently loaded at full resolution. By scaling it at load time before converting it to a texture, we'd save a lot of video memory, and accelerate the background drawing process by a big factor.
4. The SDL_HINT_RENDER_SCALE_QUALITY is set to linear, which is pretty expensive. Supporting the *nearest* algorithm would increase the performance by a large factor, and if the window is not resized, the textures will appear smoothly at 1:1 scale.
5. If the worst come to worst, decrease the frame rate. I'd rather avoid that, it's like admitting defeat.

**Comment by lanodan** [comment]
> Accelerated Graphics are a lie
I think it should be named GPU/Hardware graphics, it’s basically made on the assumption that the GPU is faster than CPU… (and there can be a lot of case where the CPU is faster…)

**Comment by fmang** [comment]
I've done what I could with the new OSHU_QUALITY environment variable. It's not perfect, but it's about playable.

Going further will require profiling and patience, but that's for a future issue.
