### ISSUE TITLE
Consider integrating some C++

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#48]
C is a great challenge, but I find myself avoiding efficient data containers like maps because it's pain to code and use in C.

I definitely wanna avoid any overkill object-oriented model with design patterns, but modern C++11 with a minimal use of OOP should already make memory management much easier.

**Comment by VPeruS** [comment]
How about https://github.com/srdja/Collections-C or maybe glib?

**Comment by fmang** [comment]
> How about https://github.com/srdja/Collections-C or maybe glib?

They're indeed worth considering, especially glib which oshu! already depends on via cairo.

In both case, you have to sacrifice type safety though.

Beside type safety, C++ has another advantage: RAII, which helps managing memory. glib provides tools for that too, but it can't beat C++.

**Comment by fmang** [comment]
The branch is ready. I'll play a bit to see if everything still works fine, but that looks good so far.

The C++ compiler exposed all kinds of implicit casts here and there. I feel bad.

**Comment by VPeruS** [comment]
You can use static_cast<type>() instead of (type) it is a little bit safer

**Comment by fmang** [comment]
@VPeruS Very good point.

I've naively migrated the code to preserve the C semantics, but as the code evolves, it should indeed use safer casts, or even better: no casts at all.

I've merged the branch into master. Let's move on from there.
