### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#53]
I haven't used a linter for oshu! so far 😇

Clang-Tidy or CppCheck can probably help detect a few potential errors. I should at least try them out of curiosity.

**Comment by VPeruS** [comment]
Additionally what about integratation of linter in pr process with travis?

**Comment by lanodan** [comment]
Maybe there could also be things like clang/LLVM ``scan-build``.

**Comment by fmang** [comment]
clang-tidy detected 2cded58. The other linters didn't find anything. Static analysis is hard eh. Beside, the typer does most of the job.

CMake integrates clang-tidy easily:

```
set_target_properties(
  my-target-name PROPERTIES
  CXX_CLANG_TIDY clang-tidy
)
```

The compilation gets very slow though.

That's it for today.
