### ISSUE TITLE
Capture official autoplays

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#56]
For issue #44, there needs to be a reference, preferably the official osu! stable game.

Sadly, I cannot run osu! on my computer so it's hard for me to compare what oshu! plays to what it should play. I've tried looking for videos on the internet, but most of them are too old to be useful.

I have listed a few potentially problematic beatmaps in #44. It doesn't have to be any particular beatmap, but it has to be a beatmap that make creative use of the sound effects. The few I've listed sound weird when played in oshu!, and could become the key to uncovering bugs.

Ideally, a cool submission would consist in the .osz file, and a video record of the autoplay mode. The quality of the video is of little importance, 480p is more than enough, and the audio just need to be good enough to distinguish the sound samples played. I can receive the files by mail, or from pretty much anywhere, and will probably host them somewhere for any other interested contributors.

Please send me a message or reply to this issue if you can help.

**Comment by lanodan** [comment]
Is it good enough to record osu!stable (the old/current one) via wine (it’s pretty stable) or to run osu!lazer (natively but probably not the latest version as it often doesn’t compile) ?

**Comment by fmang** [comment]
osu!stable via wine is good enough. It's not like Wine would make it
play different sounds.

osu!lazer won't do though. Last time I checked the code, the logic on
sound effects missed a few elements.

**Comment by jamesguessis** [comment]
https://youtu.be/BAsVQqXPpzc does something like this work?

**Comment by fmang** [comment]
@jamesguessis Yep, that's pretty much what I had in mind. I am now confident oshu's parser is missing something important. Thank you.

For the first song, I've noticed it started playing with basic noisy sounds, and right after you restarted it, it then played soft sound effects on hit objects. Most videos on YouTube have those noisy sounds too. Is that a popular skin, or like the default sound effects for replay (to hear the keys better)?

**Comment by jamesguessis** [comment]
That's just the skin, a static hitsound for better accuracy. 
I do want to note I play with 50% music 100% effect, which is what was in that video
you could possibly add the option to ignore beatmap hitsounds like osu does as well?

**Comment by fmang** [comment]
Got it.

Yes, I'd like the replays with the default skin too.

The static hitsound erases some precious information, but on the positive side, it makes it explicit when the skin is used instead of the beatmap's custom hitsounds.

**Comment by jamesguessis** [comment]
https://youtu.be/T0nWaWQEhxk guess this should do well

I think I did the same maps in the same order, just default skin this time

**Comment by fmang** [comment]
Perfect! Thank you very much.

I'm closing the issue. Now I gotta work on #44.
