### ISSUE TITLE
-GN skin

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#58]
Suggested by @jamesguessis:
> That's just the skin, a static hitsound for better accuracy. (-GN's skin if you want to use it for testing?)
> I do want to note I play with 50% music 100% effect, which is what was in that video
> you could possibly add the option to ignore beatmap hitsounds like osu does as well?

In fact, it is easy to change the skin by replacing the wav files in  `share/samples` in the distribution tarball, or by updating  `$PREFIX/share/oshu/samples` after it is installed. However, it manual and undocumented.

Let's also note that this -GN skin uses the same sample for everything, so there's a big potential optimization here. *But* let's not fall in the trap of premature optimization.

If the skin is free enough though, we could ship it with oshu.

**Comment by jamesguessis** [comment]
there's plenty of popular skins that I believe you could ship with without issues, tho I think you might need to find one where everything skinnable is skinned (to possibly use as a sort of fallback, since I assume that's what osu! does)

**Comment by fmang** [comment]
I've included a minimal GN-like skin for the default installation, solving this issue.

Remains to add a more advanced skin management to restore the previous default skin.
