### ISSUE TITLE
--version option

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#66]
`oshu --version` is expected by most people to print the version number. Today it doesn't, because the option is not recognized.

The version number is still displayed in --help and in the man page, but it's a cheap thing to add.

**Comment by VPeruS** [comment]
gonna work by yourself? This may also include moving from getopt

**Comment by fmang** [comment]
I don't plan to move away from getopt right now.

For Windows, I consider maintaining a different binary unless I find a
nice getopt alternative. We'll see.
