### ISSUE TITLE
Be more specific with the requirements

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#72]
ffmpeg, SDL2, cairo and all are nice, but not all versions are supported.

It'd be nice if the README were more accurate and specified the minimum required version for each dependency.

That kind of thing is hard to test, and the changelogs may help, but nothing beats experience.

**Comment by fmang** [comment]
6c24184

I've added the versions I use, but I'm sure we could lower the requirements.

**Comment by lanodan** [comment]
I use the following versions (and it works fine):

* libSDL2 2.0.5+ (2.0.4 doesn’t works)
* cmake 3.9.6
* FFmpeg 3.3.6 (which is apparently ABI-compatible up-to 3.2.6 and maybe older)
* cairo 1.14.8
* pango 1.40.14

**Comment by fmang** [comment]
Thank you :)
c40c7d9
