### ISSUE TITLE
Library package

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#73]
For the beatmap indexer (#35), and skin management, there's probably going to be a `~/.oshu` directory popping out soon. What should we call it?

This directory will certainly contain skins and beatmaps.

I think it makes sense to group skin discovery and beatmaps discovery in the same directory, since in both case the job is to scan the filesystem and find files or directories. Not only the user's home directory but also the oshu! installation directory.

The module would define namespaces like `oshu::library::beatmaps` and `oshu::library::skins`, and depend on the beatmap and audio modules I guess.

Related to #67.

**Comment by lanodan** [comment]
I think the directory should try to follow XDG specifications, it doesn’t really hurt anyway and I think it could allow neat things (like data dir in removable storage).
So beatmaps, skins … in ``${XDG_DATA_DIR:-$HOME/.local/share}`` and configuration in ``${XDG_CONF_DIR:-$HOME/.config}``.

**Comment by fmang** [comment]
The module is here, with the beatmaps sub-module. The skins sub-module will probably be added to library along with #67.

The XDG_DATA_DIR is already used for the oshu! installation, but I don't think it's a good idea to have the user wander about in .local to look for beatmaps. `~/.oshu` sounds like a more natural place to extract all your beatmaps, even though it contributes to the home directory pollution :/
