### ISSUE TITLE
Load backgrounds with ImageMagick

### ISSUE THREAD

**Issue by fmang** [fmang/oshu#79]
The current background loader uses SDL_Image to decode the picture, and then Cairo to prescale it with a complex dance.

ImageMagick can do the job just fine, and more easily. We'll probably need ImageMagick sooner or later anyway with #78, so we might as well ditch SDL_Image while we're at it.

**Comment by lanodan** [comment]
I’d go against ImageMagick (same goes for GraphicsMagick) as it got quite a history of security issues and theses backgrounds aren’t from the user.
And it would introduce yet another dependency while ffmpeg or SDL are probably able to do it too (maybe with a bit more of work tho).

**Comment by fmang** [comment]
You probably have ImageTragick in mind. It's true it's a significant
issue.

I'm positive SDL can't help here, but ffmpeg can do the work just fine
indeed. Not only has it got an absurd amount of decoders and encoders,
it's also got as many filters. https://trac.ffmpeg.org/wiki/Scaling
