### ISSUE TITLE
Osu account without game

### ISSUE THREAD

**Issue by sdsddsd1** [fmang/oshu#88]
I hope this is ok to ask:
Downloading beatmaps from the official osu page is not possible without an account. However I cant create an account without the original game which I cant install because of dependencies.
Maybe you know a workaround?
Greetings.

**Comment by fmang** [comment]
That’s lame. They didn’t use to force installing the game to create an
account. I’ll see what can be done.

Meanwhile, there exists alternative beatmap sources, like https://bloodcat.com/osu/

**Comment by fmang** [comment]
I raised the issue to the osu! team but they won’t listen. Alternative osu! implementations are not something they consider, I guess. Their API looks simple enough so I’m sure one could easily make a shell script to create osu! accounts.

I think Bloodcat is good enough though, so I just added a mention in the README (commit d99629d68336ba72924fe5a97eaedc073661be24). If for some reason Bloodcat doesn’t cut it, please let me know.

**Comment by sdsddsd1** [comment]
Nice, thank you!
Oshu! is now  packaged in my game repo for KISS linux.
