### ISSUE TITLE
ffmpeg cannot open the stream file

### ISSUE THREAD

**Issue by unknown989** [fmang/oshu#92]
when I run the game using this command <br>`./oshu Kaori\ Oda\ -\ Zero\ Tokei\ \(Short\ ver.\)\ \(ShogunMoon\)\ \[Shining\].osu`
I get :
`ERROR: failed opening the stream file`
`ERROR: ffmpeg error: No such file or directory`
`ERROR: no audio, aborting`
`CRITICAL: could not open the audio device`

**Comment by fmang** [comment]
.osu files are not standalone : they need their audio track in the same directory.

Looks like you’re trying to play the sample .osu file in the test directory, which is voluntarily left incomplete. You need to find your beatmaps elsewhere. See the README.

**Comment by unknown989** [comment]
Yeah thanks, i found that out,
I was going to close and answer the issue but i forgot.
