### ISSUE TITLE
modules not found

### ISSUE THREAD

**Issue by faizu396** [fmang/oshu#94]
I'm using a Raspberry Pi 4 with Raspberry Pi OS 32 bit (based on debian bullseye). When I run the cmake command, it says libavformat, libavcodec, libswresample, and libavutil are all not found. I looked these up and it says they all come with ffmpeg. This is confusing because I already have ffmpeg installed and it is the latest version available (7:4.3.4-0+deb11u1+rpt1), which is already newer than the required version 3.3.6. Do I have to install those individually or reinstall ffmpeg or something?

**Comment by Eragonfr** [comment]
Did you installed the -dev version of ffmpeg ? If not you will be missing all dev files from it, including headers files that are required  to find the dependencies.

**Comment by fmang** [comment]
Closing the issue for inactivity. I think you got the right answer @Eragonfr, merci !
