### ISSUE TITLE
Several required dependencies for building saying not found in apt package manager apt. 

### ISSUE THREAD

**Issue by SpyrosTheBoss** [fmang/oshu#97]
Please send me a command for the apt command to install all required dependencies for building in arm64.

**Comment by fmang** [comment]
I can’t. Many distributions use apt as package manager, and there’s no universal package naming scheme. You need to figure out the right packages for your distribution by using apt search or something similar. I suggest you use your distribution’s graphical tools if you are not familial with the command line.

Please also learn some étiquette when opening issues, like describing your environment, posting the build logs, and looking for information on your own.
